# Generated by Django 5.0.1 on 2024-02-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0002_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='facebook_page',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
